<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Installation script for imbrex
 *
 * @author No-CMS Module Generator
 */
class Info extends CMS_Module {

    //////////////////////////////////////////////////////////////////////////////
    // NAVIGATIONS
    //////////////////////////////////////////////////////////////////////////////
    protected $NAVIGATIONS = array(
            // Imbrex
            array(
                'navigation_name'   => 'index',
                'url'               => 'imbrex',
                'authorization_id'  => PRIV_EVERYONE,
                'default_layout'    => 'minimal',
                'title'             => 'Imbrex',
                'parent_name'       => NULL,
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-th-large',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),

            // Browse Series
            array(
                'navigation_name'   => 'browse_imbrex_filedesc_seriesstmt',
                'url'               => 'browse_imbrex_filedesc_seriesstmt',
                'authorization_id'  => PRIV_EVERYONE,
                'default_layout'    => NULL,
                'title'             => 'View Series',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => NULL,
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Browse Edition
            array(
                'navigation_name'   => 'browse_imbrex_filedesc',
                'url'               => 'browse_imbrex_filedesc',
                'authorization_id'  => PRIV_EVERYONE,
                'default_layout'    => NULL,
                'title'             => 'View Editions',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => NULL,
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Browse Text
            array(
                'navigation_name'   => 'browse_imbrex_text',
                'url'               => 'browse_imbrex_text',
                'authorization_id'  => PRIV_EVERYONE,
                'default_layout'    => NULL,
                'title'             => 'Paratext',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => NULL,
                'notification_url'  => NULL,
                'hidden'            => 1,
                'static_content'    => NULL,
            ),
            // Browse Page
            array(
                'navigation_name'   => 'browse_imbrex_text_body_lg',
                'url'               => 'browse_imbrex_text_body_lg',
                'authorization_id'  => PRIV_EVERYONE,
                'default_layout'    => 'minimal',
                'title'             => 'Text+Tiles',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => NULL,
                'notification_url'  => NULL,
                'hidden'            => 1,
                'static_content'    => NULL,
            ),

            // Browse Assign edition to Editors
            array(
                'navigation_name'   => 'browse_imbrex_mte_jobs',
                'url'               => 'browse_imbrex_mte_jobs',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => NULL,
                'title'             => 'Editor Dashboard',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-user',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
         
            //Manage Tile
            array(
                'navigation_name'   => 'edit_imbrex_tile',
                'url'               => 'edit_imbrex_tile',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Manage Tile',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-th-large',
                'notification_url'  => NULL,
                'hidden'            => 1,
                'static_content'    => NULL,
            ),
        );

    protected $BACKEND_NAVIGATIONS = array(		

            // Manage Series
            array(
                'entity_name'       => 'imbrex_filedesc_seriesstmt',
                'url'               => 'manage_imbrex_filedesc_seriesstmt',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Manage Series',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-th-list',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Labels
            array(
                'entity_name'       => 'imbrex_text_labels',
                'url'               => 'manage_imbrex_text_labels',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Emergency: Series Labels',
                'parent_name'       => 'manage_imbrex_filedesc_seriesstmt',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-tags',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Edition
            array(
                'entity_name'       => 'imbrex_filedesc',
                'url'               => 'manage_imbrex_filedesc',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Manage Editions',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-text-height',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Text
            array(
                'entity_name'       => 'imbrex_text',
                'url'               => 'manage_imbrex_text',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Emergency: Manage Step2',
                'parent_name'       => 'manage_imbrex_filedesc',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-book',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Page
            array(
                'entity_name'       => 'imbrex_text_body_lg',
                'url'               => 'manage_imbrex_text_body_lg',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Manage Pages',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-file',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Tiles
            array(
                'entity_name'       => 'imbrex_tiles',
                'url'               => 'manage_imbrex_tiles',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Manage Tiled Pages',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-th-large',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),            
			// Manage Shapes
            array(
                'entity_name'       => 'imbrex_text_shapes',
                'url'               => 'manage_imbrex_text_shapes',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Emengency: Shapes',
                'parent_name'       => 'manage_imbrex_tiles',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-edit',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Selections
            array(
                'entity_name'       => 'imbrex_text_selections',
                'url'               => 'manage_imbrex_text_selections',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Emergency: Selections',
                'parent_name'       => 'manage_imbrex_tiles',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-align-left',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            // Manage Page Labels
            array(
                'entity_name'       => 'imbrex_page_labels',
                'url'               => 'manage_imbrex_page_labels',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Emergency: Labels',
                'parent_name'       => 'manage_imbrex_tiles',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-tags',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            ),
            

            // Manage Assign edition to Editors
            array(
                'entity_name'       => 'imbrex_mte_jobs',
                'url'               => 'manage_imbrex_mte_jobs',
                'authorization_id'  => PRIV_AUTHORIZED,
                'default_layout'    => 'minimal',
                'title'             => 'Assign Jobs to Editors',
                'parent_name'       => 'index',
                'index'             => NULL,
                'description'       => NULL,
                'bootstrap_glyph'   => 'glyphicon-cog',
                'notification_url'  => NULL,
                'hidden'            => NULL,
                'static_content'    => NULL,
            )            
        );

    //////////////////////////////////////////////////////////////////////////////
    // CONFIGURATIONS
    //////////////////////////////////////////////////////////////////////////////
    protected $CONFIGS = array();

    //////////////////////////////////////////////////////////////////////////////
    // PRIVILEGES
    //////////////////////////////////////////////////////////////////////////////
    protected $PRIVILEGES = array();

    //////////////////////////////////////////////////////////////////////////////
    // GROUPS
    //////////////////////////////////////////////////////////////////////////////
    protected $GROUPS = array(
            array('group_name' => 'Imbrex Manager', 'description' => 'Imbrex Manager crates Series and Editions, he assigns Editions to Editors'),
            array('group_name' => 'Imbrex Editor', 'description' => 'Imbrex Editor works in Editions assigned by Manager.'),
        );
    protected $GROUP_NAVIGATIONS = array(
		'Imbrex Manager' => array('index','browse_imbrex_filedesc_seriesstmt', 'browse_imbrex_filedesc','browse_imbrex_text','browse_imbrex_text_body_lg','browse_imbrex_mte_jobs','edit_imbrex_tile'),
		'Imbrex Editor' => array('index','browse_imbrex_filedesc','browse_imbrex_text','browse_imbrex_text_body_lg','edit_imbrex_tile')
		);
		
    protected $GROUP_BACKEND_NAVIGATIONS = array(
            'Imbrex Manager' => 
				array('imbrex_filedesc_seriesstmt', 'imbrex_filedesc', 'imbrex_text', 'imbrex_text_body_lg', 'imbrex_text_shapes', 'imbrex_text_selections', 'imbrex_page_labels', 'imbrex_text_labels', 'imbrex_mte_jobs', 'imbrex_tiles'),
            'Imbrex Editor' => 
				array('imbrex','imbrex_filedesc', 'imbrex_text', 'imbrex_text_body_lg','imbrex_text_shapes', 'imbrex_text_selections', 'imbrex_page_labels', 'imbrex_text_labels','imbrex_tiles')            
        );
    protected $GROUP_PRIVILEGES = array();
    protected $GROUP_BACKEND_PRIVILEGES = array(
            'Imbrex Manager' => array(
                'imbrex_filedesc_seriesstmt' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_labels' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_filedesc' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_body_lg' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
				'imbrex_text_shapes' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_selections' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_page_labels' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_tiles' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_tile' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_mte_jobs' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
            ),
            'Imbrex Editor' => array(
                'imbrex_filedesc_seriesstmt' => array('read', 'print', 'export'),
                'imbrex_text_labels' => array('read', 'print', 'export'),
                'imbrex_filedesc' => array('read', 'edit', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text' => array('read', 'add', 'edit', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_body_lg' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_shapes' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_text_selections' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_page_labels' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_tiles' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_tile' => array('read', 'add', 'edit', 'delete', 'list', 'back_to_list', 'print', 'export'),
                'imbrex_mte_jobs' => array('read'),                
            )
        );

    //////////////////////////////////////////////////////////////////////////////
    // TABLES and DATA
    //////////////////////////////////////////////////////////////////////////////
    protected $TABLES = array(
        // imbrex_filedesc_seriesstmt
        'imbrex_filedesc_seriesstmt' => array(
            'key'    => 'series_id',
            'fields' => array(
                'series_id'            => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'public'               => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 0),
                'featured'             => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 0),
                'idno'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'title'                => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'description'          => array("type" => 'text',       "null" => TRUE),
                'respstmt'             => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'logo'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'cover'                => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'labels'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_filedesc_seriesstmt_idno
        'imbrex_filedesc_seriesstmt_idno' => array(
            'key'    => 'idno_id',
            'fields' => array(
                'idno_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'series_id'            => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('ISBN','ISSN','DOI','URI'), "null" => TRUE),
                'idno'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_filedesc_seriesstmt_respstmt
        'imbrex_filedesc_seriesstmt_respstmt' => array(
            'key'    => 'resp_id',
            'fields' => array(
                'resp_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'series_id'            => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'resp'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_filedesc
        'imbrex_filedesc' => array(
            'key'    => 'ed_id',
            'fields' => array(
                'ed_id'                => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'xml_id'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'public'               => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 0),
                'featured'             => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 0),
                'seriesstmt'           => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'titlestmt_title'      => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'titlestmt_author'     => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'titlestmt_editor'     => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'titlestmt_respstmt'   => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'publicationstmt_publisher' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'publicationstmt_pubplace' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'publicationstmt_date' => array("type" => 'int',        "constraint" => 4,   "null" => TRUE),
                'publicationstmt_authority' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'publicationstmt_availability' => array("type" => 'text',       "null" => TRUE),
                'sourcedesc_biblstruct_analytic_title' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_analytic_author' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_analytic_editor' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_monogr_title' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_monogr_imprint_pubplace' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_monogr_imprint_publisher' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_monogr_imprint_date' => array("type" => 'int',        "constraint" => 4,   "null" => TRUE),
                'sourcedesc_biblstruct_monogr_imprint_biblscope_vol' => array("type" => 'int',        "constraint" => 4,   "null" => TRUE),
                'sourcedesc_biblstruct_monogr_imprint_biblscope_pp' => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
                'sourcedesc_biblstruct_monogr_extent' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'sourcedesc_biblstruct_idno' => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_titlestmt_author
        'imbrex_titlestmt_author' => array(
            'key'    => 'author_id',
            'fields' => array(
                'author_id'            => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_titlestmt_editor
        'imbrex_titlestmt_editor' => array(
            'key'    => 'editor_id',
            'fields' => array(
                'editor_id'            => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_titlestmt_respstmt
        'imbrex_titlestmt_respstmt' => array(
            'key'    => 'resp_id',
            'fields' => array(
                'resp_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'resp'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_publicationstmt_publisher
        'imbrex_publicationstmt_publisher' => array(
            'key'    => 'publisher_id',
            'fields' => array(
                'publisher_id'         => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'publisher'            => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'address'              => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'target'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_analytic_author
        'imbrex_analytic_author' => array(
            'key'    => 'author_id',
            'fields' => array(
                'author_id'            => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_analytic_editor
        'imbrex_analytic_editor' => array(
            'key'    => 'editor_id',
            'fields' => array(
                'editor_id'            => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('pers','org'), "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'key'                  => array("type" => 'varchar',    "constraint" => 10,  "null" => TRUE),
            ),
        ),
        // imbrex_biblstruct_idno
        'imbrex_biblstruct_idno' => array(
            'key'    => 'idno_id',
            'fields' => array(
                'idno_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('ISBN','ISSN','DOI','URI'), "null" => TRUE),
                'idno'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_languages
        'imbrex_languages' => array(
            'key'    => 'language_id',
            'fields' => array(
                'language_id'          => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'code'                 => array("type" => 'varchar',    "constraint" => 3,   "null" => TRUE),
                'language'             => array("type" => 'varchar',    "constraint" => 64,  "null" => TRUE),
            ),
        ),
        // imbrex_text
        'imbrex_text' => array(
            'key'    => 'text_id',
            'fields' => array(
                'text_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'xml_id'               => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'text_type'            => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'text_lang'            => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'body_note'            => array("type" => 'text',       "null" => TRUE),
                'linebreak'           => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 1),
                'page_id'              => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_text_body_lg
        'imbrex_text_body_lg' => array(
            'key'    => 'page_id',
            'fields' => array(
                'page_id'              => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'xml_id'               => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'file'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'pagenum'              => array("type" => 'int',        "constraint" => 5,   "null" => TRUE),
				'linebreaks'           => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 1),
                'pagecontent'          => array("type" => 'text',       "null" => TRUE),
                'closed'           	   => array("type" => 'tinyint',    "constraint" => 1, "null" => FALSE, "default" => 0),
                'shapes'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'selections'           => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'labels'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'text_id'              => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
            ),
        ),
        // imbrex_text_shapes
        'imbrex_text_shapes' => array(
            'key'    => 'shape_id',
            'fields' => array(
                'shape_id'                   => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'page_id'              => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'id'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'type'                 => array("type" => 'enum',    "constraint" => array('rect','ellipse'), "null" => TRUE),
                '_scale'               => array("type" => 'varchar',    "constraint" => 60,  "null" => TRUE),
                'color'                => array("type" => 'varchar',    "constraint" => 7,   "null" => TRUE),
                'posinfo_x_cx'         => array("type" => 'varchar',    "constraint" => 60,  "null" => TRUE),
                'posinfo_y_cy'         => array("type" => 'varchar',    "constraint" => 60,  "null" => TRUE),
                'posinfo_width_rx'     => array("type" => 'varchar',    "constraint" => 60,  "null" => TRUE),
                'posinfo_height_ry'    => array("type" => 'varchar',    "constraint" => 60,  "null" => TRUE),
                'labels'         => array("type" => 'text',       "null" => TRUE),
                'lines'         => array("type" => 'text',       "null" => TRUE),
            ),
        ),
        // imbrex_text_selections
        'imbrex_text_selections' => array(
            'key'    => 'selection_id',
            'fields' => array(
                'selection_id'                   => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'page_id'              => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'id'                   => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'startparent'          => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'startoffset'          => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'startchild'           => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'endparent'            => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'endoffset'            => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'endchild'             => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'color'                => array("type" => 'varchar',    "constraint" => 7,   "null" => TRUE),
                'labels'               => array("type" => 'text',       "null" => TRUE),
            ),
        ),
        // imbrex_page_labels
        'imbrex_page_labels' => array(
            'key'    => 'label_id',
            'fields' => array(
                'label_id'             => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'page_id'              => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'id'                   => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'selections'           => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'shapes'               => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),        
        // imbrex_text_labels
        'imbrex_text_labels' => array(
            'key'    => 'label_id',
            'fields' => array(
                'label_id'                   => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'series_id'            => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),                
                'id'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
                'name'                 => array("type" => 'varchar',    "constraint" => 255, "null" => TRUE),
            ),
        ),
        // imbrex_mte_jobs
        'imbrex_mte_jobs' => array(
            'key'    => 'mte_job_id',
            'fields' => array(
                'mte_job_id'           => 'TYPE_INT_UNSIGNED_AUTO_INCREMENT',
                'ed_id'                => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
                'user_id'              => array("type" => 'int',        "constraint" => 20,  "null" => TRUE),
            ),
        )
    );
    protected $DATA = array(
    
        'imbrex_languages' => array(
            array('language_id' => '1', 'code' => 'aar', 'language' => 'Afar'),
            array('language_id' => '2', 'code' => 'abk', 'language' => 'Abkhazian'),
            array('language_id' => '3', 'code' => 'ace', 'language' => 'Achinese'),
            array('language_id' => '4', 'code' => 'ach', 'language' => 'Acoli'),
            array('language_id' => '5', 'code' => 'ada', 'language' => 'Adangme'),
            array('language_id' => '6', 'code' => 'ady', 'language' => 'Adyghe; Adygei'),
            array('language_id' => '7', 'code' => 'afa', 'language' => 'Afro-Asiatic languages'),
            array('language_id' => '8', 'code' => 'afh', 'language' => 'Afrihili'),
            array('language_id' => '9', 'code' => 'afr', 'language' => 'Afrikaans'),
            array('language_id' => '10', 'code' => 'ain', 'language' => 'Ainu'),
            array('language_id' => '11', 'code' => 'aka', 'language' => 'Akan'),
            array('language_id' => '12', 'code' => 'akk', 'language' => 'Akkadian'),
            array('language_id' => '13', 'code' => 'alb', 'language' => 'Albanian'),
            array('language_id' => '14', 'code' => 'ale', 'language' => 'Aleut'),
            array('language_id' => '15', 'code' => 'alg', 'language' => 'Algonquian languages'),
            array('language_id' => '16', 'code' => 'alt', 'language' => 'Southern Altai'),
            array('language_id' => '17', 'code' => 'amh', 'language' => 'Amharic'),
            array('language_id' => '18', 'code' => 'ang', 'language' => 'English, Old (ca.450-1100)'),
            array('language_id' => '19', 'code' => 'anp', 'language' => 'Angika'),
            array('language_id' => '20', 'code' => 'apa', 'language' => 'Apache languages'),
            array('language_id' => '21', 'code' => 'ara', 'language' => 'Arabic'),
            array('language_id' => '22', 'code' => 'arc', 'language' => 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
            array('language_id' => '23', 'code' => 'arg', 'language' => 'Aragonese'),
            array('language_id' => '24', 'code' => 'arm', 'language' => 'Armenian'),
            array('language_id' => '25', 'code' => 'arn', 'language' => 'Mapudungun; Mapuche'),
            array('language_id' => '26', 'code' => 'arp', 'language' => 'Arapaho'),
            array('language_id' => '27', 'code' => 'art', 'language' => 'Artificial languages'),
            array('language_id' => '28', 'code' => 'arw', 'language' => 'Arawak'),
            array('language_id' => '29', 'code' => 'asm', 'language' => 'Assamese'),
            array('language_id' => '30', 'code' => 'ast', 'language' => 'Asturian; Bable; Leonese; Asturleonese'),
            array('language_id' => '31', 'code' => 'ath', 'language' => 'Athapascan languages'),
            array('language_id' => '32', 'code' => 'aus', 'language' => 'Australian languages'),
            array('language_id' => '33', 'code' => 'ava', 'language' => 'Avaric'),
            array('language_id' => '34', 'code' => 'ave', 'language' => 'Avestan'),
            array('language_id' => '35', 'code' => 'awa', 'language' => 'Awadhi'),
            array('language_id' => '36', 'code' => 'aym', 'language' => 'Aymara'),
            array('language_id' => '37', 'code' => 'aze', 'language' => 'Azerbaijani'),
            array('language_id' => '38', 'code' => 'bad', 'language' => 'Banda languages'),
            array('language_id' => '39', 'code' => 'bai', 'language' => 'Bamileke languages'),
            array('language_id' => '40', 'code' => 'bak', 'language' => 'Bashkir'),
            array('language_id' => '41', 'code' => 'bal', 'language' => 'Baluchi'),
            array('language_id' => '42', 'code' => 'bam', 'language' => 'Bambara'),
            array('language_id' => '43', 'code' => 'ban', 'language' => 'Balinese'),
            array('language_id' => '44', 'code' => 'baq', 'language' => 'Basque'),
            array('language_id' => '45', 'code' => 'bas', 'language' => 'Basa'),
            array('language_id' => '46', 'code' => 'bat', 'language' => 'Baltic languages'),
            array('language_id' => '47', 'code' => 'bej', 'language' => 'Beja; Bedawiyet'),
            array('language_id' => '48', 'code' => 'bel', 'language' => 'Belarusian'),
            array('language_id' => '49', 'code' => 'bem', 'language' => 'Bemba'),
            array('language_id' => '50', 'code' => 'ben', 'language' => 'Bengali'),
            array('language_id' => '51', 'code' => 'ber', 'language' => 'Berber languages'),
            array('language_id' => '52', 'code' => 'bho', 'language' => 'Bhojpuri'),
            array('language_id' => '53', 'code' => 'bih', 'language' => 'Bihari languages'),
            array('language_id' => '54', 'code' => 'bik', 'language' => 'Bikol'),
            array('language_id' => '55', 'code' => 'bin', 'language' => 'Bini; Edo'),
            array('language_id' => '56', 'code' => 'bis', 'language' => 'Bislama'),
            array('language_id' => '57', 'code' => 'bla', 'language' => 'Siksika'),
            array('language_id' => '58', 'code' => 'bnt', 'language' => 'Bantu (Other)'),
            array('language_id' => '59', 'code' => 'bos', 'language' => 'Bosnian'),
            array('language_id' => '60', 'code' => 'bra', 'language' => 'Braj'),
            array('language_id' => '61', 'code' => 'bre', 'language' => 'Breton'),
            array('language_id' => '62', 'code' => 'btk', 'language' => 'Batak languages'),
            array('language_id' => '63', 'code' => 'bua', 'language' => 'Buriat'),
            array('language_id' => '64', 'code' => 'bug', 'language' => 'Buginese'),
            array('language_id' => '65', 'code' => 'bul', 'language' => 'Bulgarian'),
            array('language_id' => '66', 'code' => 'bur', 'language' => 'Burmese'),
            array('language_id' => '67', 'code' => 'byn', 'language' => 'Blin; Bilin'),
            array('language_id' => '68', 'code' => 'cad', 'language' => 'Caddo'),
            array('language_id' => '69', 'code' => 'cai', 'language' => 'Central American Indian languages'),
            array('language_id' => '70', 'code' => 'car', 'language' => 'Galibi Carib'),
            array('language_id' => '71', 'code' => 'cat', 'language' => 'Catalan; Valencian'),
            array('language_id' => '72', 'code' => 'cau', 'language' => 'Caucasian languages'),
            array('language_id' => '73', 'code' => 'ceb', 'language' => 'Cebuano'),
            array('language_id' => '74', 'code' => 'cel', 'language' => 'Celtic languages'),
            array('language_id' => '75', 'code' => 'cha', 'language' => 'Chamorro'),
            array('language_id' => '76', 'code' => 'chb', 'language' => 'Chibcha'),
            array('language_id' => '77', 'code' => 'che', 'language' => 'Chechen'),
            array('language_id' => '78', 'code' => 'chg', 'language' => 'Chagatai'),
            array('language_id' => '79', 'code' => 'chi', 'language' => 'Chinese'),
            array('language_id' => '80', 'code' => 'chk', 'language' => 'Chuukese'),
            array('language_id' => '81', 'code' => 'chm', 'language' => 'Mari'),
            array('language_id' => '82', 'code' => 'chn', 'language' => 'Chinook jargon'),
            array('language_id' => '83', 'code' => 'cho', 'language' => 'Choctaw'),
            array('language_id' => '84', 'code' => 'chp', 'language' => 'Chipewyan; Dene Suline'),
            array('language_id' => '85', 'code' => 'chr', 'language' => 'Cherokee'),
            array('language_id' => '86', 'code' => 'chu', 'language' => 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
            array('language_id' => '87', 'code' => 'chv', 'language' => 'Chuvash'),
            array('language_id' => '88', 'code' => 'chy', 'language' => 'Cheyenne'),
            array('language_id' => '89', 'code' => 'cmc', 'language' => 'Chamic languages'),
            array('language_id' => '90', 'code' => 'cop', 'language' => 'Coptic'),
            array('language_id' => '91', 'code' => 'cor', 'language' => 'Cornish'),
            array('language_id' => '92', 'code' => 'cos', 'language' => 'Corsican'),
            array('language_id' => '93', 'code' => 'cpe', 'language' => 'Creoles and pidgins, English based'),
            array('language_id' => '94', 'code' => 'cpf', 'language' => 'Creoles and pidgins, French-based '),
            array('language_id' => '95', 'code' => 'cpp', 'language' => 'Creoles and pidgins, Portuguese-based '),
            array('language_id' => '96', 'code' => 'cre', 'language' => 'Cree'),
            array('language_id' => '97', 'code' => 'crh', 'language' => 'Crimean Tatar; Crimean Turkish'),
            array('language_id' => '98', 'code' => 'crp', 'language' => 'Creoles and pidgins '),
            array('language_id' => '99', 'code' => 'csb', 'language' => 'Kashubian'),
            array('language_id' => '100', 'code' => 'cus', 'language' => 'Cushitic languages'),
            array('language_id' => '101', 'code' => 'cze', 'language' => 'Czech'),
            array('language_id' => '102', 'code' => 'dak', 'language' => 'Dakota'),
            array('language_id' => '103', 'code' => 'dan', 'language' => 'Danish'),
            array('language_id' => '104', 'code' => 'dar', 'language' => 'Dargwa'),
            array('language_id' => '105', 'code' => 'day', 'language' => 'Land Dayak languages'),
            array('language_id' => '106', 'code' => 'del', 'language' => 'Delaware'),
            array('language_id' => '107', 'code' => 'den', 'language' => 'Slave (Athapascan)'),
            array('language_id' => '108', 'code' => 'dgr', 'language' => 'Dogrib'),
            array('language_id' => '109', 'code' => 'din', 'language' => 'Dinka'),
            array('language_id' => '110', 'code' => 'div', 'language' => 'Divehi; Dhivehi; Maldivian'),
            array('language_id' => '111', 'code' => 'doi', 'language' => 'Dogri'),
            array('language_id' => '112', 'code' => 'dra', 'language' => 'Dravidian languages'),
            array('language_id' => '113', 'code' => 'dsb', 'language' => 'Lower Sorbian'),
            array('language_id' => '114', 'code' => 'dua', 'language' => 'Duala'),
            array('language_id' => '115', 'code' => 'dum', 'language' => 'Dutch, Middle (ca.1050-1350)'),
            array('language_id' => '116', 'code' => 'dut', 'language' => 'Dutch; Flemish'),
            array('language_id' => '117', 'code' => 'dyu', 'language' => 'Dyula'),
            array('language_id' => '118', 'code' => 'dzo', 'language' => 'Dzongkha'),
            array('language_id' => '119', 'code' => 'efi', 'language' => 'Efik'),
            array('language_id' => '120', 'code' => 'egy', 'language' => 'Egyptian (Ancient)'),
            array('language_id' => '121', 'code' => 'eka', 'language' => 'Ekajuk'),
            array('language_id' => '122', 'code' => 'elx', 'language' => 'Elamite'),
            array('language_id' => '123', 'code' => 'eng', 'language' => 'English'),
            array('language_id' => '124', 'code' => 'enm', 'language' => 'English, Middle (1100-1500)'),
            array('language_id' => '125', 'code' => 'epo', 'language' => 'Esperanto'),
            array('language_id' => '126', 'code' => 'est', 'language' => 'Estonian'),
            array('language_id' => '127', 'code' => 'ewe', 'language' => 'Ewe'),
            array('language_id' => '128', 'code' => 'ewo', 'language' => 'Ewondo'),
            array('language_id' => '129', 'code' => 'fan', 'language' => 'Fang'),
            array('language_id' => '130', 'code' => 'fao', 'language' => 'Faroese'),
            array('language_id' => '131', 'code' => 'fat', 'language' => 'Fanti'),
            array('language_id' => '132', 'code' => 'fij', 'language' => 'Fijian'),
            array('language_id' => '133', 'code' => 'fil', 'language' => 'Filipino; Pilipino'),
            array('language_id' => '134', 'code' => 'fin', 'language' => 'Finnish'),
            array('language_id' => '135', 'code' => 'fiu', 'language' => 'Finno-Ugrian languages'),
            array('language_id' => '136', 'code' => 'fon', 'language' => 'Fon'),
            array('language_id' => '137', 'code' => 'fre', 'language' => 'French'),
            array('language_id' => '138', 'code' => 'frm', 'language' => 'French, Middle (ca.1400-1600)'),
            array('language_id' => '139', 'code' => 'fro', 'language' => 'French, Old (842-ca.1400)'),
            array('language_id' => '140', 'code' => 'frr', 'language' => 'Northern Frisian'),
            array('language_id' => '141', 'code' => 'frs', 'language' => 'Eastern Frisian'),
            array('language_id' => '142', 'code' => 'fry', 'language' => 'Western Frisian'),
            array('language_id' => '143', 'code' => 'ful', 'language' => 'Fulah'),
            array('language_id' => '144', 'code' => 'fur', 'language' => 'Friulian'),
            array('language_id' => '145', 'code' => 'gaa', 'language' => 'Ga'),
            array('language_id' => '146', 'code' => 'gay', 'language' => 'Gayo'),
            array('language_id' => '147', 'code' => 'gba', 'language' => 'Gbaya'),
            array('language_id' => '148', 'code' => 'gem', 'language' => 'Germanic languages'),
            array('language_id' => '149', 'code' => 'geo', 'language' => 'Georgian'),
            array('language_id' => '150', 'code' => 'ger', 'language' => 'German'),
            array('language_id' => '151', 'code' => 'gez', 'language' => 'Geez'),
            array('language_id' => '152', 'code' => 'gil', 'language' => 'Gilbertese'),
            array('language_id' => '153', 'code' => 'gla', 'language' => 'Gaelic; Scottish Gaelic'),
            array('language_id' => '154', 'code' => 'gle', 'language' => 'Irish'),
            array('language_id' => '155', 'code' => 'glg', 'language' => 'Galician'),
            array('language_id' => '156', 'code' => 'glv', 'language' => 'Manx'),
            array('language_id' => '157', 'code' => 'gmh', 'language' => 'German, Middle High (ca.1050-1500)'),
            array('language_id' => '158', 'code' => 'goh', 'language' => 'German, Old High (ca.750-1050)'),
            array('language_id' => '159', 'code' => 'gon', 'language' => 'Gondi'),
            array('language_id' => '160', 'code' => 'gor', 'language' => 'Gorontalo'),
            array('language_id' => '161', 'code' => 'got', 'language' => 'Gothic'),
            array('language_id' => '162', 'code' => 'grb', 'language' => 'Grebo'),
            array('language_id' => '163', 'code' => 'grc', 'language' => 'Greek, Ancient (to 1453)'),
            array('language_id' => '164', 'code' => 'gre', 'language' => 'Greek, Modern (1453-)'),
            array('language_id' => '165', 'code' => 'grn', 'language' => 'Guarani'),
            array('language_id' => '166', 'code' => 'gsw', 'language' => 'Swiss German; Alemannic; Alsatian'),
            array('language_id' => '167', 'code' => 'guj', 'language' => 'Gujarati'),
            array('language_id' => '168', 'code' => 'gwi', 'language' => 'Gwich\'in'),
            array('language_id' => '169', 'code' => 'hai', 'language' => 'Haida'),
            array('language_id' => '170', 'code' => 'hat', 'language' => 'Haitian; Haitian Creole'),
            array('language_id' => '171', 'code' => 'hau', 'language' => 'Hausa'),
            array('language_id' => '172', 'code' => 'haw', 'language' => 'Hawaiian'),
            array('language_id' => '173', 'code' => 'heb', 'language' => 'Hebrew'),
            array('language_id' => '174', 'code' => 'her', 'language' => 'Herero'),
            array('language_id' => '175', 'code' => 'hil', 'language' => 'Hiligaynon'),
            array('language_id' => '176', 'code' => 'him', 'language' => 'Himachali languages; Western Pahari languages'),
            array('language_id' => '177', 'code' => 'hin', 'language' => 'Hindi'),
            array('language_id' => '178', 'code' => 'hit', 'language' => 'Hittite'),
            array('language_id' => '179', 'code' => 'hmn', 'language' => 'Hmong; Mong'),
            array('language_id' => '180', 'code' => 'hmo', 'language' => 'Hiri Motu'),
            array('language_id' => '181', 'code' => 'hrv', 'language' => 'Croatian'),
            array('language_id' => '182', 'code' => 'hsb', 'language' => 'Upper Sorbian'),
            array('language_id' => '183', 'code' => 'hun', 'language' => 'Hungarian'),
            array('language_id' => '184', 'code' => 'hup', 'language' => 'Hupa'),
            array('language_id' => '185', 'code' => 'iba', 'language' => 'Iban'),
            array('language_id' => '186', 'code' => 'ibo', 'language' => 'Igbo'),
            array('language_id' => '187', 'code' => 'ice', 'language' => 'Icelandic'),
            array('language_id' => '188', 'code' => 'ido', 'language' => 'Ido'),
            array('language_id' => '189', 'code' => 'iii', 'language' => 'Sichuan Yi; Nuosu'),
            array('language_id' => '190', 'code' => 'ijo', 'language' => 'Ijo languages'),
            array('language_id' => '191', 'code' => 'iku', 'language' => 'Inuktitut'),
            array('language_id' => '192', 'code' => 'ile', 'language' => 'Interlingue; Occidental'),
            array('language_id' => '193', 'code' => 'ilo', 'language' => 'Iloko'),
            array('language_id' => '194', 'code' => 'ina', 'language' => 'Interlingua (International Auxiliary Language Association)'),
            array('language_id' => '195', 'code' => 'inc', 'language' => 'Indic languages'),
            array('language_id' => '196', 'code' => 'ind', 'language' => 'Indonesian'),
            array('language_id' => '197', 'code' => 'ine', 'language' => 'Indo-European languages'),
            array('language_id' => '198', 'code' => 'inh', 'language' => 'Ingush'),
            array('language_id' => '199', 'code' => 'ipk', 'language' => 'Inupiaq'),
            array('language_id' => '200', 'code' => 'ira', 'language' => 'Iranian languages'),
            array('language_id' => '201', 'code' => 'iro', 'language' => 'Iroquoian languages'),
            array('language_id' => '202', 'code' => 'ita', 'language' => 'Italian'),
            array('language_id' => '203', 'code' => 'jav', 'language' => 'Javanese'),
            array('language_id' => '204', 'code' => 'jbo', 'language' => 'Lojban'),
            array('language_id' => '205', 'code' => 'jpn', 'language' => 'Japanese'),
            array('language_id' => '206', 'code' => 'jpr', 'language' => 'Judeo-Persian'),
            array('language_id' => '207', 'code' => 'jrb', 'language' => 'Judeo-Arabic'),
            array('language_id' => '208', 'code' => 'kaa', 'language' => 'Kara-Kalpak'),
            array('language_id' => '209', 'code' => 'kab', 'language' => 'Kabyle'),
            array('language_id' => '210', 'code' => 'kac', 'language' => 'Kachin; Jingpho'),
            array('language_id' => '211', 'code' => 'kal', 'language' => 'Kalaallisut; Greenlandic'),
            array('language_id' => '212', 'code' => 'kam', 'language' => 'Kamba'),
            array('language_id' => '213', 'code' => 'kan', 'language' => 'Kannada'),
            array('language_id' => '214', 'code' => 'kar', 'language' => 'Karen languages'),
            array('language_id' => '215', 'code' => 'kas', 'language' => 'Kashmiri'),
            array('language_id' => '216', 'code' => 'kau', 'language' => 'Kanuri'),
            array('language_id' => '217', 'code' => 'kaw', 'language' => 'Kawi'),
            array('language_id' => '218', 'code' => 'kaz', 'language' => 'Kazakh'),
            array('language_id' => '219', 'code' => 'kbd', 'language' => 'Kabardian'),
            array('language_id' => '220', 'code' => 'kha', 'language' => 'Khasi'),
            array('language_id' => '221', 'code' => 'khi', 'language' => 'Khoisan languages'),
            array('language_id' => '222', 'code' => 'khm', 'language' => 'Central Khmer'),
            array('language_id' => '223', 'code' => 'kho', 'language' => 'Khotanese; Sakan'),
            array('language_id' => '224', 'code' => 'kik', 'language' => 'Kikuyu; Gikuyu'),
            array('language_id' => '225', 'code' => 'kin', 'language' => 'Kinyarwanda'),
            array('language_id' => '226', 'code' => 'kir', 'language' => 'Kirghiz; Kyrgyz'),
            array('language_id' => '227', 'code' => 'kmb', 'language' => 'Kimbundu'),
            array('language_id' => '228', 'code' => 'kok', 'language' => 'Konkani'),
            array('language_id' => '229', 'code' => 'kom', 'language' => 'Komi'),
            array('language_id' => '230', 'code' => 'kon', 'language' => 'Kongo'),
            array('language_id' => '231', 'code' => 'kor', 'language' => 'Korean'),
            array('language_id' => '232', 'code' => 'kos', 'language' => 'Kosraean'),
            array('language_id' => '233', 'code' => 'kpe', 'language' => 'Kpelle'),
            array('language_id' => '234', 'code' => 'krc', 'language' => 'Karachay-Balkar'),
            array('language_id' => '235', 'code' => 'krl', 'language' => 'Karelian'),
            array('language_id' => '236', 'code' => 'kro', 'language' => 'Kru languages'),
            array('language_id' => '237', 'code' => 'kru', 'language' => 'Kurukh'),
            array('language_id' => '238', 'code' => 'kua', 'language' => 'Kuanyama; Kwanyama'),
            array('language_id' => '239', 'code' => 'kum', 'language' => 'Kumyk'),
            array('language_id' => '240', 'code' => 'kur', 'language' => 'Kurdish'),
            array('language_id' => '241', 'code' => 'kut', 'language' => 'Kutenai'),
            array('language_id' => '242', 'code' => 'lad', 'language' => 'Ladino'),
            array('language_id' => '243', 'code' => 'lah', 'language' => 'Lahnda'),
            array('language_id' => '244', 'code' => 'lam', 'language' => 'Lamba'),
            array('language_id' => '245', 'code' => 'lao', 'language' => 'Lao'),
            array('language_id' => '246', 'code' => 'lat', 'language' => 'Latin'),
            array('language_id' => '247', 'code' => 'lav', 'language' => 'Latvian'),
            array('language_id' => '248', 'code' => 'lez', 'language' => 'Lezghian'),
            array('language_id' => '249', 'code' => 'lim', 'language' => 'Limburgan; Limburger; Limburgish'),
            array('language_id' => '250', 'code' => 'lin', 'language' => 'Lingala'),
            array('language_id' => '251', 'code' => 'lit', 'language' => 'Lithuanian'),
            array('language_id' => '252', 'code' => 'lol', 'language' => 'Mongo'),
            array('language_id' => '253', 'code' => 'loz', 'language' => 'Lozi'),
            array('language_id' => '254', 'code' => 'ltz', 'language' => 'Luxembourgish; Letzeburgesch'),
            array('language_id' => '255', 'code' => 'lua', 'language' => 'Luba-Lulua'),
            array('language_id' => '256', 'code' => 'lub', 'language' => 'Luba-Katanga'),
            array('language_id' => '257', 'code' => 'lug', 'language' => 'Ganda'),
            array('language_id' => '258', 'code' => 'lui', 'language' => 'Luiseno'),
            array('language_id' => '259', 'code' => 'lun', 'language' => 'Lunda'),
            array('language_id' => '260', 'code' => 'luo', 'language' => 'Luo (Kenya and Tanzania)'),
            array('language_id' => '261', 'code' => 'lus', 'language' => 'Lushai'),
            array('language_id' => '262', 'code' => 'mac', 'language' => 'Macedonian'),
            array('language_id' => '263', 'code' => 'mad', 'language' => 'Madurese'),
            array('language_id' => '264', 'code' => 'mag', 'language' => 'Magahi'),
            array('language_id' => '265', 'code' => 'mah', 'language' => 'Marshallese'),
            array('language_id' => '266', 'code' => 'mai', 'language' => 'Maithili'),
            array('language_id' => '267', 'code' => 'mak', 'language' => 'Makasar'),
            array('language_id' => '268', 'code' => 'mal', 'language' => 'Malayalam'),
            array('language_id' => '269', 'code' => 'man', 'language' => 'Mandingo'),
            array('language_id' => '270', 'code' => 'mao', 'language' => 'Maori'),
            array('language_id' => '271', 'code' => 'map', 'language' => 'Austronesian languages'),
            array('language_id' => '272', 'code' => 'mar', 'language' => 'Marathi'),
            array('language_id' => '273', 'code' => 'mas', 'language' => 'Masai'),
            array('language_id' => '274', 'code' => 'may', 'language' => 'Malay'),
            array('language_id' => '275', 'code' => 'mdf', 'language' => 'Moksha'),
            array('language_id' => '276', 'code' => 'mdr', 'language' => 'Mandar'),
            array('language_id' => '277', 'code' => 'men', 'language' => 'Mende'),
            array('language_id' => '278', 'code' => 'mga', 'language' => 'Irish, Middle (900-1200)'),
            array('language_id' => '279', 'code' => 'mic', 'language' => 'Mi\'kmaq; Micmac'),
            array('language_id' => '280', 'code' => 'min', 'language' => 'Minangkabau'),
            array('language_id' => '281', 'code' => 'mis', 'language' => 'Uncoded languages'),
            array('language_id' => '282', 'code' => 'mkh', 'language' => 'Mon-Khmer languages'),
            array('language_id' => '283', 'code' => 'mlg', 'language' => 'Malagasy'),
            array('language_id' => '284', 'code' => 'mlt', 'language' => 'Maltese'),
            array('language_id' => '285', 'code' => 'mnc', 'language' => 'Manchu'),
            array('language_id' => '286', 'code' => 'mni', 'language' => 'Manipuri'),
            array('language_id' => '287', 'code' => 'mno', 'language' => 'Manobo languages'),
            array('language_id' => '288', 'code' => 'moh', 'language' => 'Mohawk'),
            array('language_id' => '289', 'code' => 'mon', 'language' => 'Mongolian'),
            array('language_id' => '290', 'code' => 'mos', 'language' => 'Mossi'),
            array('language_id' => '291', 'code' => 'mul', 'language' => 'Multiple languages'),
            array('language_id' => '292', 'code' => 'mun', 'language' => 'Munda languages'),
            array('language_id' => '293', 'code' => 'mus', 'language' => 'Creek'),
            array('language_id' => '294', 'code' => 'mwl', 'language' => 'Mirandese'),
            array('language_id' => '295', 'code' => 'mwr', 'language' => 'Marwari'),
            array('language_id' => '296', 'code' => 'myn', 'language' => 'Mayan languages'),
            array('language_id' => '297', 'code' => 'myv', 'language' => 'Erzya'),
            array('language_id' => '298', 'code' => 'nah', 'language' => 'Nahuatl languages'),
            array('language_id' => '299', 'code' => 'nai', 'language' => 'North American Indian languages'),
            array('language_id' => '300', 'code' => 'nap', 'language' => 'Neapolitan'),
            array('language_id' => '301', 'code' => 'nau', 'language' => 'Nauru'),
            array('language_id' => '302', 'code' => 'nav', 'language' => 'Navajo; Navaho'),
            array('language_id' => '303', 'code' => 'nbl', 'language' => 'Ndebele, South; South Ndebele'),
            array('language_id' => '304', 'code' => 'nde', 'language' => 'Ndebele, North; North Ndebele'),
            array('language_id' => '305', 'code' => 'ndo', 'language' => 'Ndonga'),
            array('language_id' => '306', 'code' => 'nds', 'language' => 'Low German; Low Saxon; German, Low; Saxon, Low'),
            array('language_id' => '307', 'code' => 'nep', 'language' => 'Nepali'),
            array('language_id' => '308', 'code' => 'new', 'language' => 'Nepal Bhasa; Newari'),
            array('language_id' => '309', 'code' => 'nia', 'language' => 'Nias'),
            array('language_id' => '310', 'code' => 'nic', 'language' => 'Niger-Kordofanian languages'),
            array('language_id' => '311', 'code' => 'niu', 'language' => 'Niuean'),
            array('language_id' => '312', 'code' => 'nno', 'language' => 'Norwegian Nynorsk; Nynorsk, Norwegian'),
            array('language_id' => '313', 'code' => 'nob', 'language' => 'Bokmål, Norwegian; Norwegian Bokmål'),
            array('language_id' => '314', 'code' => 'nog', 'language' => 'Nogai'),
            array('language_id' => '315', 'code' => 'non', 'language' => 'Norse, Old'),
            array('language_id' => '316', 'code' => 'nor', 'language' => 'Norwegian'),
            array('language_id' => '317', 'code' => 'nqo', 'language' => 'N\'Ko'),
            array('language_id' => '318', 'code' => 'nso', 'language' => 'Pedi; Sepedi; Northern Sotho'),
            array('language_id' => '319', 'code' => 'nub', 'language' => 'Nubian languages'),
            array('language_id' => '320', 'code' => 'nwc', 'language' => 'Classical Newari; Old Newari; Classical Nepal Bhasa'),
            array('language_id' => '321', 'code' => 'nya', 'language' => 'Chichewa; Chewa; Nyanja'),
            array('language_id' => '322', 'code' => 'nym', 'language' => 'Nyamwezi'),
            array('language_id' => '323', 'code' => 'nyn', 'language' => 'Nyankole'),
            array('language_id' => '324', 'code' => 'nyo', 'language' => 'Nyoro'),
            array('language_id' => '325', 'code' => 'nzi', 'language' => 'Nzima'),
            array('language_id' => '326', 'code' => 'oci', 'language' => 'Occitan (post 1500); Provençal'),
            array('language_id' => '327', 'code' => 'oji', 'language' => 'Ojibwa'),
            array('language_id' => '328', 'code' => 'ori', 'language' => 'Oriya'),
            array('language_id' => '329', 'code' => 'orm', 'language' => 'Oromo'),
            array('language_id' => '330', 'code' => 'osa', 'language' => 'Osage'),
            array('language_id' => '331', 'code' => 'oss', 'language' => 'Ossetian; Ossetic'),
            array('language_id' => '332', 'code' => 'ota', 'language' => 'Turkish, Ottoman (1500-1928)'),
            array('language_id' => '333', 'code' => 'oto', 'language' => 'Otomian languages'),
            array('language_id' => '334', 'code' => 'paa', 'language' => 'Papuan languages'),
            array('language_id' => '335', 'code' => 'pag', 'language' => 'Pangasinan'),
            array('language_id' => '336', 'code' => 'pal', 'language' => 'Pahlavi'),
            array('language_id' => '337', 'code' => 'pam', 'language' => 'Pampanga; Kapampangan'),
            array('language_id' => '338', 'code' => 'pan', 'language' => 'Panjabi; Punjabi'),
            array('language_id' => '339', 'code' => 'pap', 'language' => 'Papiamento'),
            array('language_id' => '340', 'code' => 'pau', 'language' => 'Palauan'),
            array('language_id' => '341', 'code' => 'peo', 'language' => 'Persian, Old (ca.600-400 B.C.)'),
            array('language_id' => '342', 'code' => 'per', 'language' => 'Persian'),
            array('language_id' => '343', 'code' => 'phi', 'language' => 'Philippine languages'),
            array('language_id' => '344', 'code' => 'phn', 'language' => 'Phoenician'),
            array('language_id' => '345', 'code' => 'pli', 'language' => 'Pali'),
            array('language_id' => '346', 'code' => 'pol', 'language' => 'Polish'),
            array('language_id' => '347', 'code' => 'pon', 'language' => 'Pohnpeian'),
            array('language_id' => '348', 'code' => 'por', 'language' => 'Portuguese'),
            array('language_id' => '349', 'code' => 'pra', 'language' => 'Prakrit languages'),
            array('language_id' => '350', 'code' => 'pro', 'language' => 'Provençal, Old (to 1500)'),
            array('language_id' => '351', 'code' => 'pus', 'language' => 'Pushto; Pashto'),
            array('language_id' => '352', 'code' => 'qaa', 'language' => 'Reserved for local use'),
            array('language_id' => '353', 'code' => 'que', 'language' => 'Quechua'),
            array('language_id' => '354', 'code' => 'raj', 'language' => 'Rajasthani'),
            array('language_id' => '355', 'code' => 'rap', 'language' => 'Rapanui'),
            array('language_id' => '356', 'code' => 'rar', 'language' => 'Rarotongan; Cook Islands Maori'),
            array('language_id' => '357', 'code' => 'roa', 'language' => 'Romance languages'),
            array('language_id' => '358', 'code' => 'roh', 'language' => 'Romansh'),
            array('language_id' => '359', 'code' => 'rom', 'language' => 'Romany'),
            array('language_id' => '360', 'code' => 'rum', 'language' => 'Romanian; Moldavian; Moldovan'),
            array('language_id' => '361', 'code' => 'run', 'language' => 'Rundi'),
            array('language_id' => '362', 'code' => 'rup', 'language' => 'Aromanian; Arumanian; Macedo-Romanian'),
            array('language_id' => '363', 'code' => 'rus', 'language' => 'Russian'),
            array('language_id' => '364', 'code' => 'sad', 'language' => 'Sandawe'),
            array('language_id' => '365', 'code' => 'sag', 'language' => 'Sango'),
            array('language_id' => '366', 'code' => 'sah', 'language' => 'Yakut'),
            array('language_id' => '367', 'code' => 'sai', 'language' => 'South American Indian (Other)'),
            array('language_id' => '368', 'code' => 'sal', 'language' => 'Salishan languages'),
            array('language_id' => '369', 'code' => 'sam', 'language' => 'Samaritan Aramaic'),
            array('language_id' => '370', 'code' => 'san', 'language' => 'Sanskrit'),
            array('language_id' => '371', 'code' => 'sas', 'language' => 'Sasak'),
            array('language_id' => '372', 'code' => 'sat', 'language' => 'Santali'),
            array('language_id' => '373', 'code' => 'scn', 'language' => 'Sicilian'),
            array('language_id' => '374', 'code' => 'sco', 'language' => 'Scots'),
            array('language_id' => '375', 'code' => 'sel', 'language' => 'Selkup'),
            array('language_id' => '376', 'code' => 'sem', 'language' => 'Semitic languages'),
            array('language_id' => '377', 'code' => 'sga', 'language' => 'Irish, Old (to 900)'),
            array('language_id' => '378', 'code' => 'sgn', 'language' => 'Sign Languages'),
            array('language_id' => '379', 'code' => 'shn', 'language' => 'Shan'),
            array('language_id' => '380', 'code' => 'sid', 'language' => 'Sidamo'),
            array('language_id' => '381', 'code' => 'sin', 'language' => 'Sinhala; Sinhalese'),
            array('language_id' => '382', 'code' => 'sio', 'language' => 'Siouan languages'),
            array('language_id' => '383', 'code' => 'sit', 'language' => 'Sino-Tibetan languages'),
            array('language_id' => '384', 'code' => 'sla', 'language' => 'Slavic languages'),
            array('language_id' => '385', 'code' => 'slo', 'language' => 'Slovak'),
            array('language_id' => '386', 'code' => 'slv', 'language' => 'Slovenian'),
            array('language_id' => '387', 'code' => 'sma', 'language' => 'Southern Sami'),
            array('language_id' => '388', 'code' => 'sme', 'language' => 'Northern Sami'),
            array('language_id' => '389', 'code' => 'smi', 'language' => 'Sami languages'),
            array('language_id' => '390', 'code' => 'smj', 'language' => 'Lule Sami'),
            array('language_id' => '391', 'code' => 'smn', 'language' => 'Inari Sami'),
            array('language_id' => '392', 'code' => 'smo', 'language' => 'Samoan'),
            array('language_id' => '393', 'code' => 'sms', 'language' => 'Skolt Sami'),
            array('language_id' => '394', 'code' => 'sna', 'language' => 'Shona'),
            array('language_id' => '395', 'code' => 'snd', 'language' => 'Sindhi'),
            array('language_id' => '396', 'code' => 'snk', 'language' => 'Soninke'),
            array('language_id' => '397', 'code' => 'sog', 'language' => 'Sogdian'),
            array('language_id' => '398', 'code' => 'som', 'language' => 'Somali'),
            array('language_id' => '399', 'code' => 'son', 'language' => 'Songhai languages'),
            array('language_id' => '400', 'code' => 'sot', 'language' => 'Sotho, Southern'),
            array('language_id' => '401', 'code' => 'spa', 'language' => 'Spanish; Castilian'),
            array('language_id' => '402', 'code' => 'srd', 'language' => 'Sardinian'),
            array('language_id' => '403', 'code' => 'srn', 'language' => 'Sranan Tongo'),
            array('language_id' => '404', 'code' => 'srp', 'language' => 'Serbian'),
            array('language_id' => '405', 'code' => 'srr', 'language' => 'Serer'),
            array('language_id' => '406', 'code' => 'ssa', 'language' => 'Nilo-Saharan languages'),
            array('language_id' => '407', 'code' => 'ssw', 'language' => 'Swati'),
            array('language_id' => '408', 'code' => 'suk', 'language' => 'Sukuma'),
            array('language_id' => '409', 'code' => 'sun', 'language' => 'Sundanese'),
            array('language_id' => '410', 'code' => 'sus', 'language' => 'Susu'),
            array('language_id' => '411', 'code' => 'sux', 'language' => 'Sumerian'),
            array('language_id' => '412', 'code' => 'swa', 'language' => 'Swahili'),
            array('language_id' => '413', 'code' => 'swe', 'language' => 'Swedish'),
            array('language_id' => '414', 'code' => 'syc', 'language' => 'Classical Syriac'),
            array('language_id' => '415', 'code' => 'syr', 'language' => 'Syriac'),
            array('language_id' => '416', 'code' => 'tah', 'language' => 'Tahitian'),
            array('language_id' => '417', 'code' => 'tai', 'language' => 'Tai languages'),
            array('language_id' => '418', 'code' => 'tam', 'language' => 'Tamil'),
            array('language_id' => '419', 'code' => 'tat', 'language' => 'Tatar'),
            array('language_id' => '420', 'code' => 'tel', 'language' => 'Telugu'),
            array('language_id' => '421', 'code' => 'tem', 'language' => 'Timne'),
            array('language_id' => '422', 'code' => 'ter', 'language' => 'Tereno'),
            array('language_id' => '423', 'code' => 'tet', 'language' => 'Tetum'),
            array('language_id' => '424', 'code' => 'tgk', 'language' => 'Tajik'),
            array('language_id' => '425', 'code' => 'tgl', 'language' => 'Tagalog'),
            array('language_id' => '426', 'code' => 'tha', 'language' => 'Thai'),
            array('language_id' => '427', 'code' => 'tib', 'language' => 'Tibetan'),
            array('language_id' => '428', 'code' => 'tig', 'language' => 'Tigre'),
            array('language_id' => '429', 'code' => 'tir', 'language' => 'Tigrinya'),
            array('language_id' => '430', 'code' => 'tiv', 'language' => 'Tiv'),
            array('language_id' => '431', 'code' => 'tkl', 'language' => 'Tokelau'),
            array('language_id' => '432', 'code' => 'tlh', 'language' => 'Klingon; tlhIngan-Hol'),
            array('language_id' => '433', 'code' => 'tli', 'language' => 'Tlingit'),
            array('language_id' => '434', 'code' => 'tmh', 'language' => 'Tamashek'),
            array('language_id' => '435', 'code' => 'tog', 'language' => 'Tonga (Nyasa)'),
            array('language_id' => '436', 'code' => 'ton', 'language' => 'Tonga (Tonga Islands)'),
            array('language_id' => '437', 'code' => 'tpi', 'language' => 'Tok Pisin'),
            array('language_id' => '438', 'code' => 'tsi', 'language' => 'Tsimshian'),
            array('language_id' => '439', 'code' => 'tsn', 'language' => 'Tswana'),
            array('language_id' => '440', 'code' => 'tso', 'language' => 'Tsonga'),
            array('language_id' => '441', 'code' => 'tuk', 'language' => 'Turkmen'),
            array('language_id' => '442', 'code' => 'tum', 'language' => 'Tumbuka'),
            array('language_id' => '443', 'code' => 'tup', 'language' => 'Tupi languages'),
            array('language_id' => '444', 'code' => 'tur', 'language' => 'Turkish'),
            array('language_id' => '445', 'code' => 'tut', 'language' => 'Altaic languages'),
            array('language_id' => '446', 'code' => 'tvl', 'language' => 'Tuvalu'),
            array('language_id' => '447', 'code' => 'twi', 'language' => 'Twi'),
            array('language_id' => '448', 'code' => 'tyv', 'language' => 'Tuvinian'),
            array('language_id' => '449', 'code' => 'udm', 'language' => 'Udmurt'),
            array('language_id' => '450', 'code' => 'uga', 'language' => 'Ugaritic'),
            array('language_id' => '451', 'code' => 'uig', 'language' => 'Uighur; Uyghur'),
            array('language_id' => '452', 'code' => 'ukr', 'language' => 'Ukrainian'),
            array('language_id' => '453', 'code' => 'umb', 'language' => 'Umbundu'),
            array('language_id' => '454', 'code' => 'und', 'language' => 'Undetermined'),
            array('language_id' => '455', 'code' => 'urd', 'language' => 'Urdu'),
            array('language_id' => '456', 'code' => 'uzb', 'language' => 'Uzbek'),
            array('language_id' => '457', 'code' => 'vai', 'language' => 'Vai'),
            array('language_id' => '458', 'code' => 'ven', 'language' => 'Venda'),
            array('language_id' => '459', 'code' => 'vie', 'language' => 'Vietnamese'),
            array('language_id' => '460', 'code' => 'vol', 'language' => 'Volapük'),
            array('language_id' => '461', 'code' => 'vot', 'language' => 'Votic'),
            array('language_id' => '462', 'code' => 'wak', 'language' => 'Wakashan languages'),
            array('language_id' => '463', 'code' => 'wal', 'language' => 'Walamo'),
            array('language_id' => '464', 'code' => 'war', 'language' => 'Waray'),
            array('language_id' => '465', 'code' => 'was', 'language' => 'Washo'),
            array('language_id' => '466', 'code' => 'wel', 'language' => 'Welsh'),
            array('language_id' => '467', 'code' => 'wen', 'language' => 'Sorbian languages'),
            array('language_id' => '468', 'code' => 'wln', 'language' => 'Walloon'),
            array('language_id' => '469', 'code' => 'wol', 'language' => 'Wolof'),
            array('language_id' => '470', 'code' => 'xal', 'language' => 'Kalmyk; Oirat'),
            array('language_id' => '471', 'code' => 'xho', 'language' => 'Xhosa'),
            array('language_id' => '472', 'code' => 'yao', 'language' => 'Yao'),
            array('language_id' => '473', 'code' => 'yap', 'language' => 'Yapese'),
            array('language_id' => '474', 'code' => 'yid', 'language' => 'Yiddish'),
            array('language_id' => '475', 'code' => 'yor', 'language' => 'Yoruba'),
            array('language_id' => '476', 'code' => 'ypk', 'language' => 'Yupik languages'),
            array('language_id' => '477', 'code' => 'zap', 'language' => 'Zapotec'),
            array('language_id' => '478', 'code' => 'zbl', 'language' => 'Blissymbols; Blissymbolics; Bliss'),
            array('language_id' => '479', 'code' => 'zen', 'language' => 'Zenaga'),
            array('language_id' => '480', 'code' => 'zgh', 'language' => 'Standard Moroccan Tamazight'),
            array('language_id' => '481', 'code' => 'zha', 'language' => 'Zhuang; Chuang'),
            array('language_id' => '482', 'code' => 'znd', 'language' => 'Zande languages'),
            array('language_id' => '483', 'code' => 'zul', 'language' => 'Zulu'),
            array('language_id' => '484', 'code' => 'zun', 'language' => 'Zuni'),
            array('language_id' => '485', 'code' => 'zxx', 'language' => 'No linguistic content; Not applicable'),
            array('language_id' => '486', 'code' => 'zza', 'language' => 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'),
        ),
    );

    //////////////////////////////////////////////////////////////////////////////
    // ACTIVATION
    //////////////////////////////////////////////////////////////////////////////
    public function do_activate(){
		
		if (!is_writable(FCPATH) AND !is_dir(FCPATH."/files")) {
			$this->ERROR_MESSAGE = "<strong>".FCPATH." is not writable.</strong> It must be writable in order to create the files/ directory.<br>Change the permissions and reload the modules management.";
		    return false;    
		}
		elseif ( is_writable(FCPATH) AND !is_dir(FCPATH."/files"))
		{
			mkdir(FCPATH."/files");			
		} 
		elseif ( is_writable(FCPATH) AND !is_writable(FCPATH."/files")) {
			$this->ERROR_MESSAGE = "The directory <strong>".FCPATH."/files</strong> exists but <em>is not writable</em>. It must be writable in order to manage your editions.<br>Change the permissions and reload the module management.";
			return false;    
		}
				
        // TODO : write your module activation script here
        $this->cms_add_quicklink($this->n('browse_imbrex_filedesc_seriesstmt'));
        $this->cms_add_quicklink($this->n('browse_imbrex_filedesc'));		
    }

    //////////////////////////////////////////////////////////////////////////////
    // DEACTIVATION
    //////////////////////////////////////////////////////////////////////////////
    public function do_deactivate(){
        // TODO : write your module deactivation script here
		$this->cms_remove_quicklink($this->n('browse_imbrex_filedesc_seriesstmt'));
        $this->cms_remove_quicklink($this->n('browse_imbrex_filedesc'));
    }

    //////////////////////////////////////////////////////////////////////////////
    // UPGRADE
    //////////////////////////////////////////////////////////////////////////////
    // TODO: write your upgrade function: do_upgrade_to_x_x_x

}
